import { NextPage } from 'next';
import Head from 'next/head';
import ClientOnly from '../../components/ClientOnly/ClientOnly';
import DefectList from '../../components/Vehicles/VehicleDefects/DefectList';
import styles from '../../styles/Home.module.css';

const Defects: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <ClientOnly>
          <DefectList />
        </ClientOnly>
      </main>
    </div>
  );
};

export default Defects;
