import { ReactNode } from 'react';
import Head from 'next/head';
import ClientOnly from '@/core/ClientOnly/ClientOnly';

type OrganisationTemplateProps = {
  header: ReactNode;
  createModal: ReactNode;
  leftColumn: ReactNode;
  rightColumn: ReactNode;
};

const OrganisationTemplate = ({
  header,
  createModal,
  leftColumn,
  rightColumn,
}: OrganisationTemplateProps) => {
  return (
    <div className="flex h-screen">
      <Head>
        <title>Fleet Management</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex flex-1 flex-col overflow-hidden">
        {header}

        {/* Main content */}
        <div className="flex flex-1 items-stretch overflow-hidden p-4">
          <main className="flex-1 overflow-y-auto">
            <section
              aria-labelledby="primary-heading"
              className="flex h-full min-w-0 flex-1 flex-col lg:order-last"
            >
              <h1 id="primary-heading" className="sr-only">
                Organisations
              </h1>
              <ClientOnly>
                {createModal}
                <div className="mx-auto w-full max-w-7xl grow lg:flex xl:px-8">
                  {/* Left sidebar & main wrapper */}
                  <div className="min-w-0 flex-1 bg-white xl:flex">
                    <div className="bg-white lg:min-w-0 lg:flex-1">
                      <div className="h-full py-6 px-4 sm:px-6 lg:px-8">
                        {/* Start main area*/}
                        <div
                          className="relative h-full"
                          style={{ minHeight: '36rem' }}
                        >
                          <div className="absolute inset-0 rounded-lg border-2 border-dashed border-gray-200">
                            {leftColumn}
                          </div>
                        </div>
                        {/* End main area */}
                      </div>
                    </div>
                    <div className="border-b border-gray-200 bg-white xl:w-64 xl:shrink-0 xl:border-b-0 xl:border-r xl:border-gray-200">
                      <div className="h-full py-6 pl-4 pr-6 sm:pl-6 lg:pl-8 xl:pl-0">
                        {/* Start left column area */}
                        <div
                          className="relative h-full"
                          style={{ minHeight: '12rem' }}
                        >
                          <div className="absolute inset-0 rounded-lg border-2 border-dashed border-gray-200">
                            {rightColumn}
                          </div>
                        </div>
                        {/* End left column area */}
                      </div>
                    </div>
                  </div>
                </div>
              </ClientOnly>
            </section>
          </main>
        </div>
      </div>
    </div>
  );
};

export default OrganisationTemplate;
