import { FC, Fragment, ReactNode } from 'react';
import Head from 'next/head';
import Navbar from 'core/Navigation/Navbar/Navbar';
import ClientOnly from 'core/ClientOnly/ClientOnly';

type LayoutProps = {
  children: ReactNode;
};

const Layout: FC<LayoutProps> = ({ children }) => {
  return (
    <Fragment>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <nav>
        <Navbar />
      </nav>

      <main>
        <ClientOnly>{children}</ClientOnly>
      </main>
    </Fragment>
  );
};

export default Layout;
