import { Fragment, ReactNode } from 'react';
import Head from 'next/head';
import Navbar from 'core/Navigation/Navbar/Navbar';
import ClientOnly from 'core/ClientOnly/ClientOnly';

type LayoutProps = {
  children: ReactNode;
  quickAction: (state: boolean) => void;
  quickActionLabel: string;
};

const Layout = ({ children, quickAction, quickActionLabel }: LayoutProps) => {
  return (
    <Fragment>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <nav>
        <Navbar quickAction={quickAction} quickActionLabel={quickActionLabel} />
      </nav>

      <main>
        <ClientOnly>{children}</ClientOnly>
      </main>
    </Fragment>
  );
};

export default Layout;
