import { Fragment, ReactNode } from 'react';
import Head from 'next/head';
import Navbar from 'core/Navigation/Navbar/Navbar';
import ClientOnly from 'core/ClientOnly/ClientOnly';

type LayoutProps = {
  children: ReactNode;
  quickAction: (state: boolean) => void;
  quickActionLabel: string;
};

const Layout = ({ children, quickAction, quickActionLabel }: LayoutProps) => {
  return (
    <div className="min-h-full">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <nav>
        <Navbar quickAction={quickAction} quickActionLabel={quickActionLabel} />
      </nav>

      <header className="bg-white shadow">
        <div className="max-w-7xl mx-auto py-6 px-4 sm:px-6 lg:px-8">
          <h1 className="text-3xl font-bold text-gray-900">Dashboard</h1>
        </div>
      </header>
      <main>
        <ClientOnly>
          <div className="max-w-7xl mx-auto py-6 sm:px-6 lg:px-8">
            {children}
          </div>
        </ClientOnly>
      </main>
    </div>
  );
};

export default Layout;
