import { NextPage } from 'next';
import Head from 'next/head';
import ClientOnly from '../components/ClientOnly/ClientOnly';
import FuelCardList from '../components/FuelCards/FuelCardList';
import Navbar from '../components/Navigation/Navbar';

const FuelCards: NextPage = () => {
  return (
    <div>
      <nav>
        <Navbar />
      </nav>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <ClientOnly>
          <FuelCardList />
        </ClientOnly>
      </main>
    </div>
  );
};
export default FuelCards;
