import { NextPage } from 'next';
import Head from 'next/head';
import { useState } from 'react';
import ClientOnly from '../components/ClientOnly/ClientOnly';
import AddFuelCardModal from '../components/FuelCards/AddFuelCardModal';
import FuelCardList from '../components/FuelCards/FuelCardList';
import Navbar from '../components/Navigation/Navbar/Navbar';
import Button from '../components/Table/Button';

const FuelCards: NextPage = () => {
  const [open, setOpen] = useState(false);

  const addFuelCardModalHandler = (state: boolean) => {
    setOpen(state);
  };

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <nav>
        <ClientOnly>
          <Navbar />
        </ClientOnly>
      </nav>

      <main>
        <ClientOnly>
          <AddFuelCardModal
            modalState={open}
            setModalState={addFuelCardModalHandler}
          />
          <Button onClick={() => addFuelCardModalHandler(true)}>
            Add Card
          </Button>
          <FuelCardList setModalState={addFuelCardModalHandler} />
        </ClientOnly>
      </main>
    </div>
  );
};
export default FuelCards;
