import type { NextPage } from 'next';
import Head from 'next/head';
import { useState } from 'react';
import ClientOnly from '../components/ClientOnly/ClientOnly';
import Navbar from '../components/Navigation/Navbar';
import AddVehicleModal from '../components/Vehicles/VehicleList/AddVehicleModal';
import VehicleList from '../components/Vehicles/VehicleList/VehicleList';
import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
  const [open, setOpen] = useState(false);

  const addVehicleModalHandler = (state: boolean) => {
    setOpen(state);
  };

  return (
    <div>
      <nav>
        <Navbar />
      </nav>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <ClientOnly>
          <AddVehicleModal
            modalState={open}
            setModalState={addVehicleModalHandler}
          />
          <VehicleList setModalState={addVehicleModalHandler} />
        </ClientOnly>
      </main>
    </div>
  );
};

export default Home;
