import { NextPage } from 'next';
import Head from 'next/head';
import { useState } from 'react';
import ClientOnly from '../components/ClientOnly/ClientOnly';
import Navbar from '../components/Navigation/Navbar';
import AddTollTagModal from '../components/TollTags/AddTollTagModal';
import TollTagList from '../components/TollTags/TollTagList';

const TollTags: NextPage = () => {
  const [open, setOpen] = useState(false);

  const addTollTagModalHandler = (state: boolean) => {
    setOpen(state);
  };

  return (
    <div>
      <nav>
        <Navbar />
      </nav>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <ClientOnly>
          <AddTollTagModal
            modalState={open}
            setModalState={addTollTagModalHandler}
          />
          <TollTagList setModalState={addTollTagModalHandler} />
        </ClientOnly>
      </main>
    </div>
  );
};
export default TollTags;
