import { NextPage } from 'next';
import Head from 'next/head';
import ClientOnly from '../components/ClientOnly/ClientOnly';
import Navbar from '../components/Navigation/Navbar';
import TollTagList from '../components/TollTags/TollTagList';

const TollTags: NextPage = () => {
  return (
    <div>
      <nav>
        <Navbar />
      </nav>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <ClientOnly>
          <TollTagList />
        </ClientOnly>
      </main>
    </div>
  );
};
export default TollTags;
